# Robot Dev Team Project
# File: mypy.ini
# Description: Mypy configuration enforcing strict typing policies.
# License: MIT
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 MCKNLY LLC

[mypy]
python_version = 3.13
warn_unused_ignores = True
warn_return_any = True
warn_redundant_casts = True
warn_unused_configs = True
strict_optional = True
ignore_missing_imports = True

[mypy-app.tests.*]
ignore_errors = True
